/*
Stock API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OK type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OK{}

// OK struct for OK
type OK struct {
	Message *string `json:"message,omitempty"`
}

// NewOK instantiates a new OK object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOK() *OK {
	this := OK{}
	return &this
}

// NewOKWithDefaults instantiates a new OK object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOKWithDefaults() *OK {
	this := OK{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *OK) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OK) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *OK) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *OK) SetMessage(v string) {
	o.Message = &v
}

func (o OK) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OK) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableOK struct {
	value *OK
	isSet bool
}

func (v NullableOK) Get() *OK {
	return v.value
}

func (v *NullableOK) Set(val *OK) {
	v.value = val
	v.isSet = true
}

func (v NullableOK) IsSet() bool {
	return v.isSet
}

func (v *NullableOK) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOK(val *OK) *NullableOK {
	return &NullableOK{value: val, isSet: true}
}

func (v NullableOK) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOK) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


